#+title: Research Ideas
#+author: Colin Williams

** Infrastructure/Local Finances/Sprawl

*** Question 1: do tax revenues from new development subsidize the maintenance of existing infrastructure?

*Model Sketch*
- Local politicians assess "impact fees" on new development that funds the construction costs of new roads, sewerage, etc (Altshuler and Gomez-Ibanez 2000)
- New development (both residential and commercial) is revenue positive: it enlarges the tax base without raising expenditures by much
- Politician (and voters) are myopic, and do not consider financial impact of future maintenance obligations
- Politician can increase probability of re-election by driving down tax rates by approving lots of new development
- Politician cannot choose to shrink the city

*Empirical Strategy*
- Naive OLS: compare per-capita tax rates observably similar cities (in levels and trends): $$\frac{T_{it}}{N_{it}} = \beta \Delta N_{it} + \phi X_{it} + \theta \Delta X_{it} + \gamma_i + \delta_t + \epsilon_{it}$$
- Theory is supported if change in population is negatively correlated with per-capita taxes conditional on observables
- Problem: tax revenue and population change are simultaneously determined. Vibrant local economy drives population growth and raises tax revenue
- Solution: check what happens to taxes when a city can't grow further. Instrument for changes in local population using the availability of undeveloped land within local jurisdiction
- Difficulty: instrument is only valid for growing cities (amount of undeveloped land unlikely to affect the rate of population decline)
- Difficulty: political boundaries often change

*Prior Literature*
- The idea of a "growth Ponzi scheme" is discussed by urban planners (e.g., Marhon 2019), some case studies but no rigorous evaluation

*** Question 2: do federal infrastructure grants and transfers induce localities to approve more (low-density) development?

*Motivation*
- There is plausibly causal relationship between interstate highways and suburbanization (Baum-Snow 2007). Federal spending decisions clearly affect local spatial equilibrium.
- My question: does it matter if state/local governments choose how to allocate infrastructure spending?
- On one hand, local govts may prioritize quality upgrades over expansion if residents are worried about congestion
- Conversely, if Q1 is true, local govts might leverage federal infrastructure money to subsidize new development

*Empirical Strategy*
- Struggling to find exogenous variation in infrastructure grants by county. Highway fund is allocated to states based on formula, but then states choose how to distribute across local jurisdictions.
- Feiveson (2015) shows that a /general/ revenue sharing program that lasted 1972-1986 apparently induced a one-to-one increase in city expenditures, much of which went towards capital outlays. Revenue was allocated by formula that resulted in variation in transfer amounts across similar cities in different states.
- Could use this program plus historic panel of U.S. roadway data (Barrington-Leigh and Adam 2016) to test whether the increase in capital outlays went towards expansion of the road network.

*** Question 3: do changes in local government spending (and taxes) affect the composition of local businesses? (updates)

*Motivation*
- We know that public investment in schools, rail transit affects housing prices (Cellini et. al 2010, Kahn 2007)
- Households have heterogenous valuations for these amenities, leading to a change in local demography ("gentrification")
- Local demography determines demands faced by local businesses. Households with high valuations for schools want child care centers; households with low valuations may patronize bars.

*Empirical Strategy*
- Use dynamic RD developed in Cellini et. al (2010) to compare counties with similar histories of school bond elections on each side of threshold
- (Might also use library bond elections, tax elections)
- Some risk of spillovers across counties: if county A approves a bond election, families w/ school-age children might move from adjacent county B to A, lowering demand for child care centers in B. 
- Problem: there isn't much variation in counts of businesses by 6-digit NAICS and county over time.


*References*

Altshuler, Alan A., and Jose A. Gomez-Ibanez. Regulation for revenue: The political economy of land use exactions. Brookings Institution Press, 2000.

Barrington-Leigh, Christopher; Millard-Ball, Adam (2016), Data from: A century of sprawl in the United States, Dryad, Dataset, https://doi.org/10.5061/dryad.3k502

Baum-Snow, Nathaniel. "Did highways cause suburbanization?." The quarterly journal of economics 122, no. 2 (2007): 775-805.

Cellini, Stephanie Riegg, Fernando Ferreira, and Jesse Rothstein. "The value of school facility investments: Evidence from a dynamic regression discontinuity design." The Quarterly Journal of Economics 125, no. 1 (2010): 215-261.

Feiveson, Laura. "General revenue sharing and public sector unions." Journal of Public Economics 125 (2015): 28-45.

Kahn, Matthew E. "Gentrification trends in new transit‐oriented communities: Evidence from 14 cities that expanded and built rail transit systems." Real Estate Economics 35, no. 2 (2007): 155-182.

Marohn Jr, Charles L. Strong towns: A bottom-up revolution to rebuild American prosperity. John Wiley & Sons, 2019.



